### ISSUE TITLE
file descriptor leak

### ISSUE THREAD

**Issue by tpepper** [clearlinux/swupd-client#121] opened 2016-08-29 18:15 UTC
swupd commands sometime show a confusing message like:

"possible file descriptor leak     fd_number="4", fd_details="socket:[######]"

**Comment by sofar** [comment] 2016-09-15 18:17
```
Possible filedescriptor leak: fd_number="5",fd_details="socket:[xxxxxxx]"
```

**Comment by phmccarty** [comment] 2016-09-15 18:29
When running on Clear Linux, some of these file descriptor leak messages come from clr-boot-manager, since it also checks for file descriptor leaks, and it inherits some open file descriptors from its parent process (swupd).

**Comment by sofar** [comment] 2016-09-15 18:32
I straced it and it's a dbus socket connection (pacrunner)

**Comment by bradTpeters** [comment] 2016-09-15 20:43
Known issue with a LOT of history.
Quick rundown:

I originally traced this back into the dbus connection opened during our curl call out for autoproxy (to pacrunner).

I authored a patch to move us to systemd-bus, but we didn't want to have a swupd dependency on an internally carried curl patch. 

In the process of pushing it to the curl ML, I spoke to David Woodhouse, who didn't like this solution. He pushed a libproxy rewrite, which once merged we should call into from swupd, dropping our autoproxy code.

It's not yet merged as of latest upstream (7.50.3), and was still getting feedback a few weeks ago when I last checked.

I had recommended disabling file desc. leak checking till we have the fix in place, but this was shot down.

For more depth and tracking, see CLEAR-1091

**Comment by bradTpeters** [comment] 2016-09-15 20:47
I poked David to see if what's happening with the libproxy patch, and will update the jira when I hear back

**Closed** 2017-04-17 22:01 UTC

**Comment by ronindesign** [comment] 2017-12-04 20:04
Why was this closed? It's still an active issue I believe:
```bash
# swupd bundle-add os-clr-on-clr
...
Path /usr/share/locale/zh_TW.Big5/LC_MESSAGES/indent.mo is missing on the file system
Path /usr/share/locale/zh_TW/LC_MESSAGES/binutils.mo is missing on the file system
Path /usr/share/locale/zh_TW/LC_MESSAGES/ld.mo is missing on the file system
        ...100%
Calling post-update helper scripts.
Possible filedescriptor leak : 6 (socket:[79761])
Bundle(s) installation done.
```

**Environment**
Host: Windows 10 v1709 (b17025.1000)
Guest: Clear Linux (Fresh live: clear-19430-live.img.xz 2017-12-04 07:18)
VMware Workstation 12 Pro (12.5.7 build-5813279)
Setup following docs per `Virtual Machine > VMware`

```bash
# uname -a
Linux foobar 4.14.3-482.native #2 SMP Thu Nov 30 12:15:31 UTC 2017 x86_64 GNU/Linux
```

**Comment by tpepper** [comment] 2017-12-04 20:36
If you're seeing it again it's probably a regression.  Pretty sure it was fixed, but it also can fairly easily regress.  Could use better test / CI.

**Comment by phmccarty** [comment] 2017-12-04 20:38
Yes, I think that is a regression. @matthewrsj Should we open a new issue to track?

**Comment by ronindesign** [comment] 2017-12-04 21:16
No problem, just wanted to contribute my experience.

Let me know if I can provide any additional debug / repro details.

**Comment by ronindesign** [comment] 2017-12-04 21:33
Actually, this may be a result of running out of disk space.
I just created new VM with same (live) image, and ran one single command `swupd bundle-add os-clr-on-clr`.
I hit several write fails around 90% complete, however on my previous VM install of the same image, the same bundle appeared to install (mostly?).
I was even able to start to install another bundle (but only got to 14% before failing on writes).

Granted, this is an expected result, since the live image virtual disk is only ~5GB:
```
# df -h
/dev/root 4.9G 4.7G 0 100% /
```

So while my personal issue is clearly no disk space, I'm not sure if `swupd` is supposed to fail the way it did in such a scenario...
Again, I can definitely create a new issue if warranted.

**Comment by ronindesign** [comment] 2017-12-04 23:07
Hmm, still got a leak on a fresh install using installer image via manual install.
Screenshot: https://i.imgur.com/ZfUv0is.png

Exact same environment above, but using blank 20 GB vmdk (still SATA, 0:1).

**Comment by matthewrsj** [comment] 2017-12-04 23:11
yes, this looks like a regression. I opened a new issue (#347) to track.

**Comment by matthewrsj** [comment] 2017-12-04 23:12
Please put any new information in the new bug (#347)
