### ISSUE TITLE
Swupd bundle-add inside a nonexistent directory returns getcwd error

### ISSUE THREAD

**Issue by xRiot** [clearlinux/swupd-client#1078] opened 2019-09-01 11:39 UTC
When executing `swupd bundle-add {bundle}` inside a deleted directory you'll get spammed with the following error:

> (...)
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
        ...100%
Calling post-update helper scripts
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Successfully installed 1 bundle

It would be useful if there was some sort of _(global?)_ fallback for `getcwd` to avoid this, or at least one in swupd.

**Comment by karthikprabhuvinod** [comment] 2019-10-10 01:03
So looks like child process inherits a bunch of stuff including current_working_directory. Looks like this issue can occur at many places. I would suggest creating a generic function which queries the current working directory whenever it is called.

We can call it before before every forking activity.

My worry is running getcwd() on parent would return the same deleted directory once it is started. Maybe we need to run **S_ISDIR** on output of **getcwd** and then we know if it exists or not and then probably recurse one level each time till we find a one existing directory. 

**My two cents:**
Dont think there is a straight forward solution for this.

**Comment by karthikprabhuvinod** [comment] 2019-10-10 01:04
@otaviobp @castulo @phmccarty what do you guys think!

**Comment by karthikprabhuvinod** [comment] 2019-10-14 18:36
Unassigning this for now. Will check further in future if needed

**Comment by otaviobp** [comment] 2020-01-21 20:09
This problems seams way harder to avoid than initially though. We can just assume then that swupd doesn't support to be run on an nonexistent directory, so I'm closing this as wont-fix

**Comment by ahkok** [comment] 2020-01-22 17:07
if `swupd` runs `getcwd()` and that fails, it should just `chdir("/");` once. This would be sufficient.

**Comment by otaviobp** [comment] 2020-01-22 17:20
Swupd never runs getcwd(). The problem is caused by multiple binaries that swupd runs so there's no way to check if it fails in an easy way. Explicitly checking that in initialization won't work too because the directory can be removed by swupd later.
Always doing a ```chdir("/")``` on initialization should work though, if we make sure all relative paths are evaluated before that.

**Closed** 2020-03-30 20:59 UTC
Labels: bug, low priority
