### ISSUE TITLE
If clearlinux default server goes down, swupd won't update from alternative mirror

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#669] opened 2018-11-01 22:28 UTC
If you set the mirror using "swupd mirror --set" command and then tries to update your system, swupd checks if the mirror isn't very outdated. In this process, if the upstream mirror is down, swupd will fail to update from the alternative mirror.

And swupd check-update will work, so versions printed are divergent.

**Comment by castulo** [comment] 2018-11-27 23:37
I cannot reproduce the bug.

If the upstream content server is down I get a negative value for _central_version_ here -> https://github.com/clearlinux/swupd-client/blob/master/src/mirror.c#L169) which causes a negative diff which will cause the mirror to be used, so everything works fine.

**Comment by otaviobp** [comment] 2018-11-27 23:45
That's true.

I realized that the problem is when the server is not responding. In that case we got stuck on that line and as the connection was already established, curl won't timeout. We need to investigate if there's a flag we could use on curl to timeout if no data was received in a period of time.

**Comment by otaviobp** [comment] 2018-12-11 17:53
Sorry. It looks like I did something wrong in my tests. Curl is timing out, so the server will fail after curl timeout. The problem is only the one you reported.

**Comment by castulo** [comment] 2018-12-12 21:22
I was finally able to recreate the original problem you were describing. The problem is being caused by two things:
1. When running any swupd operation one of the first thing swupd does is to run soup_init to initialize itself. One of the things swupd_init does is to test the connection with the server, however it does not set any timeout for curl before attempting the test, therefore if the server is not responding curl hangs forever.
2. If a mirror is set and responding, and the server is hung, we should really allow swupd to continue since it should not need the server since the mirror is set.

**Comment by castulo** [comment] 2018-12-12 22:40
yeah, I have a patch ready, the only problem is that the tests are built on top of some PRs that have not merged. I will submit it like this and will rebase when those ones are merged.

**Closed** 2018-12-27 17:34 UTC
Labels: bug, low priority
