### ISSUE TITLE
bundle-add tab completion for bundle name

### ISSUE THREAD

**Issue by tpepper** [clearlinux/swupd-client#373] opened 2018-01-26 18:13 UTC
^^ would be nice to have

**Comment by icarus-sparry** [comment] 2018-01-26 18:19
We should have tab completion, but only if you are running as root.

```
# swupd bundle-add 
Display all 138 possibilities? (y or n)
-h                       database-basic           os-cloudguest-aws
--help                   database-basic-dev       os-cloudguest-azure
-u                       desktop                  os-cloudguest-gce
--url                    desktop-apps             os-cloudguest-vmware
....```

The list of bundle names (strictly the list in the currently downloaded MoM, so you might want to make sure you are up-to-date first) is not available to non-root.

bundle-remove also has completion.

**Comment by tpepper** [comment] 2018-01-26 18:21
Oooh I'm in a container w/o CAP_SYS_ADMIN.  Damnation.

/close

**Comment by tpepper** [comment] 2018-01-26 18:22
Hmm..actually even with CAP_SYS_ADMIN it's not working.  I've done a swupd search so info should be downloaded.

**Comment by icarus-sparry** [comment] 2018-01-26 18:32
If you attempt completion once (to load the function) and then run ```type _swupd``` you will see the code. It looks like this for the bundle-add case

```
            "bundle-add")
                if [ -r /var/lib/swupd/version ] &&
                    installed=$(</var/lib/swupd/version) &&
                    [ -r /var/lib/swupd/$installed/Manifest.MoM ]; then
                    opts+="$( sed '1,/^$/d; s/^.*\t/ /' /var/lib/swupd/$installed/Manifest.MoM | 
                                     LC_ALL=C sort )";
                fi
            ;;
```

So it tries to read /var/lib/swupd/version, to get the current release number, then read the Manifest.Mom, edit it to remove the header and everything up to the last tab, then sort the results and add it to the list of options.

So with `CAP_SYS_ADMIN` does  `if [  -r /var/lib/swupd/version ] ; then echo readable ; fi` say you can read the file or not?

**Comment by tpepper** [comment] 2018-01-26 18:40
It does not say readable.

**Comment by icarus-sparry** [comment] 2018-01-26 18:59
Hopefully with the files there, completion works?

If you don't have the cached information for the list of packages then the completion code doesn't have any data to work with.

We deliberately do not attempt to retrieve the list of packages when you are doing completion. You wouldn't like it to pause to download over a bit of wet string when completing.

I suppose we could print a warning message if version is not available, it would muck up the console output if you had started to name something i.e. `swupd bundle-add os<tab>` .

You could ask your container provider to preserve `/var/lib/swupd/version` and `/var/lib/swupd/$version/Manifest.MoM`. We could get the version from `/usr/lib/os-release` but we do need the `Manifest.MoM.`

**Comment by tpepper** [comment] 2018-01-26 19:11
Yeah it works after.  I feel like we bumped against some parts of this before and fixed what happens when you do an install.  These days I'm living inside a container more often.  ClearLinux is the container provider.

**Comment by matthewrsj** [comment] 2018-02-27 20:58
Closing since it looks like the issue is resolved. If there is a usability issue here feel free to open another issue.

**Comment by icarus-sparry** [comment] 2018-02-27 21:04
I think this is yet to be resolved, we want the copy of the MoM moved to somewhere that is readable to non-root users.

**Comment by tpepper** [comment] 2018-03-01 23:40
It would be nice if a copy of the MoM was always in /usr but it's also a
chicken and egg.  We abstracted things such that the OS content was 100%
defined by a devops flow _before_ the running of swupd-server, which is
good for reproducibility and for security too since you only read a MoM
from a trusted location.  For the MoM to be trusted and in /usr, it should
be manifested in a bundle which is manifested in the MoM.  Recursion!   It
would come down to a question of how much you worry about an attack on the
MoM parser.

**Comment by matthewrsj** [comment] 2018-04-15 03:40
This appears to work on my system now thanks to the patch from @icarus-sparry

**Closed by matthewrsj** 2018-04-15 03:40 UTC
