### ISSUE TITLE
Failed to load 12390 xfce4-desktop manifest

### ISSUE THREAD

**Issue by MrProblic** [clearlinux/swupd-client#172] opened 2016-12-30 18:58 UTC
Dear all,

Please let me report an issue related to swupd manifest of xfce4-desktop.

PHENOMENON

Can not install 'os-utils-gui' bundle due to 'Failed to load 12390 xfce4-desktop manifest'.

HOW TO RE-PRODUCE

- Newly install VirtualBox VDI from live image.
- Run:
   $ swupd update
   $ swupd bundle-add kernel-lts
   $ clr-boot-manager set-timeout 10
   $ clr-boot-manager update
   $ reboot #boot into 4.4 lts
   $ clr-boot-manager set-timeout 0
   $ clr-boot-manager update
   $ swupd bundle-add os-utils-gui os-core storage-utils

> Result
swupd-client bundle adder 3.7.4
   Copyright (C) 2012-2016 Intel Corporation
Attempting to download version string to memory
Failed to load 12390 xfce4-desktop manifest
Failed to load 12390 xfce4-desktop manifest
Failed to load 12390 xfce4-desktop manifest
Failed to load 12390 xfce4-desktop manifest
Unable to download manifest xfce4-desktop version 12390, exiting now

WORKAROUND

- Run:
   $ swupd search xfce4

> Result
Downloading Clear Linux manifests
   19.06 MB total...
Warning: Downloading missing manifest for bundle xfce4-desktop version 12390.
Cannot load official manifest MoM for version 12390
Completed manifests download.
... # xcfe4 search result as usual

   $ swupd bundle-add os-utils-gui

> Result
swupd-client bundle adder 3.7.4
   Copyright (C) 2012-2016 Intel Corporation
Downloading packs...
Attempting to download version string to memory
Downloading os-utils-gui pack for version 12380
Extracting pack.
Downloading xfce4-desktop pack for version 12390
Extracting pack.
Downloading cryptography pack for version 12380
Extracting pack.
Installing bundle(s) files...
Calling post-update helper scripts.
Bundle(s) installation done.

Thank you.
Best regards,

Luck

**Comment by phmccarty** [comment] 2017-01-04 18:10
@MrProblic Are you running swupd on a Clear Linux OS image?

If so, I see the xfce4-desktop manifest for 12390 on the server. It lives at https://download.clearlinux.org/update/12390/Manifest.xfce4-desktop.tar.

The `bundle-add` and `search` commands follow the same code path for downloading/loading manifests, so it's not clear to me how `search` is downloading the manifest, but `bundle-add` is not able to.

**Comment by MrProblic** [comment] 2017-01-05 08:12
@phmccarty 

> Are you running swupd on a Clear Linux OS image?
[Luck]: Yes I am. At thattime, I think the version is 12390.

> The bundle-add and search commands follow the same code path for downloading/loading manifests, so it's not clear to me how search is downloading the manifest, but bundle-add is not able to.
[Luck]: I'm sorry that I also don't have many clues about this. However, the phenomenon is same as I mentioned above:
1. Install os-utils-gui: failed to install xfce4
(I went to this step after canceling a installation process before to boot up to lts kernel. And try this command several times).

2. Try to search for "xfce4" then see the abnormal warning:
_Warning: Downloading missing manifest for bundle xfce4-desktop version 12390._

3. Try to install os-utils-gui again: success now.

As a result, I thought about some kind of unmatched manifest issue.

If you see any unclear point, please let me know.
Thank you.
Best regards,

Luck.

**Comment by phmccarty** [comment] 2017-09-27 18:00
I apologize for not following up on this issue.

Today, I spent some time revisiting the steps to reproduce and re-analyzing the manifests for version 12390. The swupd-server content appears okay for that build, so my best guess is that you were encountering a swupd-client bug.

In a newer version ([v3.8.6](https://github.com/clearlinux/swupd-client/releases/tag/v3.8.6), released in Clear Linux build 14470), an issue was fixed to clean up corrupt manifests in the state directory. The "warning" you saw when running `swupd search xfce4` seems to indicate that this error recovery path was executed. Sometimes this error path is run when users previously interrupt swupd-client operations with CTRL-C, since swupd-client does not handle SIGINT and therefore the state directory may be left in a corrupt state as a result.

If a build >= 14470 does not fix your issue, then I recommend running `rm -rf /var/lib/swupd` to blow away the state directory, and then try to reproduce again.

If you can still reproduce the issue afterwards, feel free to reopen.

**Closed by phmccarty** 2017-09-27 18:00 UTC
