### ISSUE TITLE
swupd update hangs when updating from a mix

### ISSUE THREAD

**Issue by chivakker** [clearlinux/swupd-client#534] opened 2018-07-26 23:34 UTC
Updated a mix with upstream.  Then build all on mix host.  Then run update from target system which is running from a usb stick with at least 55% (~16GB) of free space.  Local rpm's are small and major bundle added is desktop.

swupd update hangs for 2+ hours with no information from command in execution about progress. htop shows swupd update consuming 100% on a 8 core system (7 cores were mostly idle).

It would be nice to know if swupd is doing something and how long it will take.  Also if it is going to take an insane amount of time, just warn the user.

**Comment by matthewrsj** [comment] 2018-08-08 15:46
So am I understanding correctly that this was a network issue on the client?

**Comment by otaviobp** [comment] 2018-10-22 21:42
Yes, this should work.

We had some network related issues in a previous version of swupd. Can you recheck if you still can reproduce this issue? If so, can you share the output of "swupd -v" and check if "swupd info" is printing the correct address of the server you are running on host?

**Comment by chivakker** [comment] 2018-10-22 22:07
This is still a problem.

Create a mix on host

$ sudo swupd -v 
swupd-client 3.18.2
   Copyright (C) 2012-2018 Intel Corporation

add desktop bundle 
$ sudo swupd bundle-add desktop

update mix (one or several times)
$ sudo mixer build all --native

Try to update the target system  

$ sudo swupd -v
swupd-client 3.18.2
   Copyright (C) 2012-2018 Intel Corporation
...

$ sudo swupd update

First attempt some errors will report: Response 200 and Response 206 on retry.

Then I remove desktop bundle from target system. 

$ sudo swupd bundle-remove desktop

$ sudo swupd update 

This one goes through and I can re-install desktop bundle

I can instrument my swupd if it helps.

**Comment by otaviobp** [comment] 2018-11-05 22:33
Setting the priority to this bug as low until we find a consistent way to reproduce the problem. After that we may reconsider.

**Comment by otaviobp** [comment] 2018-11-09 18:36
Reviewing the data sent I realized that this issue is a duplicate of #598
So I'm closing this one.
@chivakker Please, keep track of that other bug.

**Closed by otaviobp** 2018-11-09 18:36 UTC
Labels: bug, low priority, need-info
