### ISSUE TITLE
Segmentation fault - swupd update - 27310 -> 27320

### ISSUE THREAD

**Issue by halars** [clearlinux/swupd-client#791] opened 2019-01-18 15:14 UTC
I get a segmentation fault, when running "swupd update":

```
# swupd update
Update started.
Preparing to update from 27310 to 27320
Downloading packs...
Segmentation fault (core dumped)
```

Any suggestions?

Installed bundles:

- acpica-unix2
- bc
- c-basic
- cloc
- cpio
- curl
- dev-utils
- diffutils
- docutils
- ethtool
- file
- findutils
- gdb
- git
- gzip
- htop
- httpd
- icdiff
- inotify-tools
- iproute2
- irssi
- kbd
- kernel-install
- less
- libX11client
- linux-tools
- llvm
- mail-utils
- mail-utils-dev
- make
- nasm
- network-basic
- nginx
- openssl
- os-core
- os-core-dev
- os-core-update
- os-core-update-dev
- os-core-webproxy
- p11-kit
- package-utils
- parallel
- patch
- perl-basic
- php-basic
- powertop
- python-basic
- python2-basic
- python3-basic
- strace
- sudo
- sysadmin-basic
- tmux
- tzdata
- unzip
- valgrind
- vim
- weechat
- which
- wpa_supplicant
- xz
- znc
- zstd

WSL: Linux 4.4.0-17763-Microsoft x86_64

**Comment by otaviobp** [comment] 2019-01-18 17:32
Hi,
Can you try to run the following command to make sure your system is sane:

    swupd verify --fix

And then:

    swupd update --debug

With this info I can try to understand what's the problem.

**Comment by halars** [comment] 2019-01-20 01:05
I had another non-wsl machine downgrade to 27300, which contains swupd 3.18.5, and just copied the swupd binary to the wsl machine, and then it works. So it seems that swupd verion 3.18.6 or 3.18.7 is the culprit.

Also "bundle-add" is broken, with the same error message, "bundle-remove" seems to work though.

**Comment by nunix** [comment] 2019-02-11 17:21
first of all, thanks a lot for raising this point, I have the same issue (trying clearlinux on WSL too) and I can confirm that the workaround of copying `swupd` from 27300 into a newer version (27700 in my case) just works fine.

For extra info, I've blogged about an "easy" way on creating distros using Docker, and therefore my base instance is based on clearlinux:latest

Thanks again for addressing this bug and seriously, clearlinux just feels super fast compared to others (standard and non-standard) distros

**Comment by jwakre** [comment] 2019-02-15 17:57
@otaviobp Those error messages happen when Swupd calls clr-boot-manager. It looks like clr-boot-manager fails to parse the kernel, so I opened an issue for that.

**Comment by jwakre** [comment] 2019-02-15 18:02
Looks similar to this clearlinux/clr-boot-manager#139

**Comment by jwakre** [comment] 2019-02-15 22:17
I don't think that the clr-boot-manger issues cause a segfault, so there is probably another issue.

**Comment by otaviobp** [comment] 2019-03-19 21:38
We are using on swupd on syscall parameter that isn't supported on WSL. I added a fallback when this parameter is missing (more information on https://github.com/clearlinux/swupd-client/pull/840/commits/b6e0bb0a73eb54579630b8c6ea6a1750d05c2640) that was merged.
Next CL release will include the fixed swupd.

Marking this bug as fixed.

**Closed by otaviobp** 2019-03-19 21:38 UTC
Labels: bug, high priority

**Comment by nunix** [comment] 2019-03-20 12:20
thanks a lot Otavio, it will prevent me copying swupd (v27300) everytime I update to a newer version.

Thanks also for taking into consideration WSL, really appreciated as ClearLinux is really working great on it :)
