### ISSUE TITLE
swupd update fails with clearlinux/stacks-dlrs-mkl

### ISSUE THREAD

**Issue by tripzero** [clearlinux/swupd-client#866] opened 2019-03-21 15:31 UTC
**Describe the bug**
swupd update fails with the following error message when running docker clearlinux/stacks-dlrs-mkl:

```
Finishing download of update content...
Staging file content
File staging failed: /usr/doc/indent
Update took 249.4 seconds
Update failed.
The command '/bin/bash -c swupd update' returned a non-zero code: 18
```

**To Reproduce**
```
docker run --rm --it clearlinux/stacks-dlrs-mkl
swupd update
```
or Dockerfile:
```
from clearlinux/stacks-dlrs-mkl
RUN swupd update

**Expected behavior**
Update completes without error

**Environment (please complete the following information):**
 - Clear Linux OS Version: 27340
 - Platform: docker 17.12.0-ce

**Comment by bryteise** [comment] 2019-03-21 15:51
New docker image resolves this issue. Please clear out the old version and retry.

**Comment by tripzero** [comment] 2019-03-21 15:55
> New docker image resolves this issue. Please clear out the old version and retry.

There is no new docker image for clearlinux/stacks-dlrs-mkl.  I see it's resolved for clearlinux.  Perhaps stacks-dlrs-mkl needs to be repushed?

**Comment by otaviobp** [comment] 2019-03-21 15:59
This isn't the same problem. But I couldn't reproduce that here. It works fine for me. Can you reproduce that consistently?

**Comment by otaviobp** [comment] 2019-03-21 16:01
Ok, it looks like it's an old bug. Closing again

**Comment by tripzero** [comment] 2019-03-22 19:46
clearlinux/stacks-dlrs-mkl is updated from 27340 to 27910.  clearlinux on the other hand has been updated to 28410.  

Issue still exists for me.  Tried on two different machines ubuntu 18.04 and 18.10.

**Comment by otaviobp** [comment] 2019-03-25 17:53
Reopening that then

**Comment by otaviobp** [comment] 2019-04-09 19:39
@tripzero Can I still assume this bug is related to having a new image? If yes, I'll close this bug.

**Comment by tripzero** [comment] 2019-04-09 19:51
Rather related to NOT having a newer image of stacks-dlrs-mkl.

**Comment by otaviobp** [comment] 2019-04-09 20:33
Oh, that's what I was trying to say. I'll close this bug then because it's out of the scope of swupd. If you reproduce this bug in an image with a current version of clear you can reopne this

**Closed by otaviobp** 2019-04-09 20:33 UTC
Labels: bug, medium priority
