### ISSUE TITLE
bundle-add returns non-zero exit code if no work needs done

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/swupd-client#510] opened 2018-06-29 23:26 UTC
If dev-utils is already installed, the following output is shown:
```
Warning: Bundle "dev-utils" is already installed, skipping it...
1 bundle was already installed
```

Returning an error code of 18.  This should return an error code of 0, much like check-update, to indicate when no work needs done.

**Comment by castulo** [comment] 2018-06-29 23:37
As part of the work done for issue #475 this error code was changed to return 18 to be consistent with the bundle-remove command.

The way it works right now, the only way to get error code of 0 using bundle-add or bundle-remove is when all bundles attempted to be added/removed are successful. If the operation does not complete because either an error occurred or the bundle was already added/removed then an error code will be returned.

**Comment by otaviobp** [comment] 2018-10-04 22:10
@castulo Can we close this one then?

**Comment by castulo** [comment] 2018-10-04 23:57
@otaviobp I think so, IMO it is working as designed, I coded it like this so it would be consistent with the errors/output from the bundle-remove command. But @matthewrsj had a discussion about this subject recently with other people that didn't agree with the way it is working, so it may be worth to see what he thinks before closing it.

**Comment by otaviobp** [comment] 2018-10-05 17:12
I'm rethinking about this problem and I vote for returning 0 in this case. If not we need 2 different codes, one for error in install and another one for "some packages were not reinstalled because they were already in the system"

**Closed** 2018-10-24 20:04 UTC
Labels: bug, medium priority
