### ISSUE TITLE
Updating fails always

### ISSUE THREAD

**Issue by Thisuu** [clearlinux/swupd-client#712] opened 2018-11-19 01:59 UTC
**Describe the bug**
I've been trying to update my system for over 2 weeks now and it always fails after reaching 83% mark.

**To Reproduce**
`sudo swupd update`

**Expected behavior**
Successfully update the system.

**Screenshots**
![screenshot from 2018-11-19 07-16-19](https://user-images.githubusercontent.com/13273054/48682026-3af83180-ebcc-11e8-8e82-6651771ca27c.png)
![screenshot from 2018-11-19 07-21-39](https://user-images.githubusercontent.com/13273054/48682033-43506c80-ebcc-11e8-8088-09843033bdc3.png)

**Environment (please complete the following information):**
 - Clear Linux OS version:
```
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=26050
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
```

 - Bundles:
```
bootloader
c-basic
cloud-api
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
domotica
ethtool
git
hardware-wifi
iproute2
kernel-native
libX11client
lua-basic
network-basic
nmap
nodejs-basic
openssl
os-core
os-core-update
p11-kit
perl-basic
powertop
python3-basic
sudo
sysadmin-basic
which
wpa_supplicant
x11-server
xemacs
zsh
```

**Comment by otaviobp** [comment] 2019-01-09 00:15
Closing this bug because as @castulo said it's a duplicate of #562
Proposed fix is under review on #767 and #761

**Closed by otaviobp** 2019-01-09 00:15 UTC
Labels: bug
