### ISSUE TITLE
Swupd update can leave files behind

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#1152] opened 2019-10-18 22:52 UTC
**Describe the bug**
Swupd update can leave files that should be deleted behind

**To Reproduce**
This bug is dependent on the content that is being update, so I tracked 2 different scenarios on how to reproduce it

Scenario 1:
    
    $ swupd os-install --path /clear -V 31090 -B desktop
    $ swupd update --path /clear -V 31300
    $ swupd diagnose --extra-files --path /clear
    ...
    Checking for extra files under /clear/root/usr
     -> Extra file: /clear/usr/share/vala/vapi/gtkspell3-3.0.vapi
     -> Extra file: /clear/usr/share/vala/vapi/gtkspell3-3.0.deps

Scenario 2:
    
    $ swupd os-install --path /clear -V 31140 -B vim
    $ swupd update --path /clear -V 31350
    $ swupd diagnose --extra-files --path /clear
    ...
    Checking for extra files under /clear/root/usr
     -> Extra file: /clear/usr/share/xml/fontconfig/fonts.dtd
     -> Extra file: /clear/usr/share/xml/fontconfig/
     -> Extra file: /clear/usr/share/xml/

**Expected behavior**
No extra files should be found

**Comment by karthikprabhuvinod** [comment] 2019-12-24 19:06
For Scenario 1:

I believe it is caused by dropping of the files by evolution bundle [ indirect dependency of desktop]

**Below command shows that files are part of bundle:**
`sudo ./swupd bundle-info evolution -V 31090 --files | grep "gtkspell3-3.0.vapi"
`

**Below command shows that files are dropped as part of bundle:**
`sudo ./swupd bundle-info evolution -V 31300 --files | grep "gtkspell3-3.0.vapi"`

**Comment by castulo** [comment] 2019-12-24 20:52
> Looks like the evolution bundle drops it as part of its manifest in 31110

so the files are just removed from the manifest without being marked for deletion?

**Comment by karthikprabhuvinod** [comment] 2019-12-24 22:19
No, they have been marked for deletion in the manifest itself

```
.d..	0000000000000000000000000000000000000000000000000000000000000000	31110	/usr/share/vala/vapi/gtkspell3-3.0.deps
.d..	0000000000000000000000000000000000000000000000000000000000000000	31110	/usr/share/vala/vapi/gtkspell3-3.0.vapi
```

**Comment by karthikprabhuvinod** [comment] 2019-12-25 00:16
Looks like those two extra files

```
 -> Extra file: /clear/usr/share/vala/vapi/gtkspell3-3.0.vapi
 -> Extra file: /clear/usr/share/vala/vapi/gtkspell3-3.0.deps
```

falls in this category:

https://github.com/clearlinux/swupd-client/blob/5efb9077ec952c1d46bf24e10a8f6b1db6daba53/src/manifest.c#L590-L593

**Comment by jwakre** [comment] 2019-12-27 22:22
The root cause is a Mixer bug that in some cases unexpectedly drops deleted file entries.

clearlinux/mixer-tools#684

**Comment by jwakre** [comment] 2020-01-03 16:57
This issue is resolved in clearlinux/mixer-tools#685.

**Comment by castulo** [comment] 2020-01-03 17:35
> This issue is resolved in [clearlinux/mixer-tools#685](https://github.com/clearlinux/mixer-tools/pull/685).

Let's just wait for @karthikprabhuvinod to confirm that fixed the issue in the swupd side before closing this bug. Thanks for looking into that @jwakre 👍

**Comment by castulo** [comment] 2020-01-03 17:36
Hmm although he would need to use its own mix to verify that 🤔 ...

**Comment by jwakre** [comment] 2020-01-03 17:41
If the swupd team wants to confirm, I documented the steps to reproduce the mix for the evolution bundle with the versions described above: clearlinux/mixer-tools#684. These steps can be run with/without the changes in my PR to reproduce the problem and prove that it was resolved.

**Comment by castulo** [comment] 2020-01-03 18:00
> If the swupd team wants to confirm, I documented the steps to reproduce the mix for the evolution bundle with the versions described above: [clearlinux/mixer-tools#684](https://github.com/clearlinux/mixer-tools/issues/684). These steps can be run with/without the changes in my PR to reproduce the problem and prove that it was resolved.

Awesome, many thanks @jwakre 🙏

**Comment by karthikprabhuvinod** [comment] 2020-01-03 18:02
@jwakre Thanks a lot.. I will verify and get back.

**Comment by karthikprabhuvinod** [comment] 2020-01-03 21:04
@jwakre, as per your suggestion, after running the mixer commands without --skip-pack & --skip-fullfile options, the diagnose works. Thanks for the fix!

**os-install**
`sudo ./swupd os-install --path /home/kp/clear -V 10 --contenturl file:///home/kp/mixer-tools/.gopath/bin/update/www --versionurl file:///home/kp/mixer-tools/.gopath/bin/update/www --nosigcheck`

**update from 10 to 30**
`sudo ./swupd update --path /home/kp/clear -V 30 --contenturl file:///home/kp/mixer-tools/.gopath/bin/update/www --versionurl file:///home/kp/mixer-tools/.gopath/bin/update/www --nosigcheck`

**diagnose**
`sudo ./swupd diagnose --extra-files --path /home/kp/clear --contenturl file:///home/kp/mixer-tools/.gopath/bin/update/www --versionurl file:///home/kp/mixer-tools/.gopath/bin/update/www --nosigcheck`

**diagnose output:**
```
Diagnosing version 30
Warning: The --nosigcheck flag was used, THE MANIFEST SIGNATURE WILL NOT BE VERIFIED
Be aware that this compromises the system security

Downloading missing manifests...

Checking for extra files under /home/kp/clear/usr

Inspected 0 files

Diagnose successful
 [100%]

```

**Comment by karthikprabhuvinod** [comment] 2020-01-03 21:05
Verified fix! closing

**Comment by karthikprabhuvinod** [comment] 2020-01-03 21:05
@jwakre : Thanks for the help & fix.

**Closed by karthikprabhuvinod** 2020-01-03 21:05 UTC
Labels: bug, medium priority
