### ISSUE TITLE
Swupd-search shouldn't fallback to old search because it is confusing and requires sudo

### ISSUE THREAD

**Issue by nsauzede** [clearlinux/swupd-client#834] opened 2019-02-28 09:03 UTC
**Is your feature request related to a problem? Please describe.**
It's really painful (insecure ?) to *have* to use sudo for some/most/any swupd search.
The "some/most/any" situation is the worst part : we can never know if this or that search would require sudo, eg: if the bundle in question is in cache (or not), also I understand that search "by file" always need to fill the cache (??)
Today, swupd search is not a local, offline, non-privileged task :
>$ sudo swupd search brand_new_bundle
>Searching for 'brand_new_bundle'
>Downloading Clear Linux manifests
>   62.70 MB total...
>Completed manifests download.
>Search term not found.
>Displaying top 5 file results per bundle

**Describe the solution you'd like**
To me, bundle searches should always use local cache; for all searches that is : by bundle "title" and by "file" (or whatever other search type)
To update the cache, I think this should be reserved to : sudo swupd update
Eg:
>$ swupd search brand_new_bundle
>Searching for 'brand_new_bundle'
>Search term not found.
>Displaying top 5 file results per bundle
>$ sudo swupd update
> ... update, update, oh! found brand_new_bundle! .. update, update
>$ swupd search brand_new_bundle
>Bundle with the best search result:
>     brand_new_bundle                          - Brand New Bundle  (42Mb)

**Describe alternatives you've considered**
The alternative is to always use sudo for such trivial searches, which seems to me very insecure if we want to reduce the potential attack/vuln surface etc..

**Additional context**
N/A

**Comment by otaviobp** [comment] 2019-02-28 20:10
I agree that there are some commands that require root and they shouldn't. But this case was already fixed with a new implementation. Can you test that in a newer Clear Linux release?

**Comment by otaviobp** [comment] 2019-02-28 20:17
And I forgot to ask you another feedback on that. Is there any other command that you think we should be able to run as a regular user? Thank you.

**Comment by nsauzede** [comment] 2019-02-28 23:04
@otaviobp I get this behaviour :
>$ cat /etc/os-release | grep VERSION_ID
>VERSION_ID=28060
>$ swupd search pdflatex
>This program must be run as root..aborting.
>$ swupd search bin/pdflatex
>This program must be run as root..aborting.

I will try to swupd update and the latest version..

**Comment by otaviobp** [comment] 2019-02-28 23:08
Thank you for the feedback. This is a bug and should be fixed. I'll rename this issue.

**Comment by otaviobp** [comment] 2019-02-28 23:13
swupd search is falling back to old swupd search when bundle isn't found. This is confusing because parameters and output is completely different. My suggestion is to remove the fallback and always use the new search. And create another command for the old search.

@fenrus75 any opinion about that?

**Comment by nsauzede** [comment] 2019-02-28 23:20
Seems like latest version doesn't change much, sudo req is inconsistent :
>$ cat /etc/os-release | grep VERSION_ID
>VERSION_ID=28070
>$ swupd search wireshark
>Bundle with the best search result:
>     wireshark                          - Network packet capture and analysis
>This bundle can be installed with:
>  swupd bundle-add  wireshark
>Alternative bundle options are
>     network-security-monitoring        - Various tools to test and improve network security
>$ swupd search pdflatex                                                        |
>This program must be run as root..aborting.
>$ swupd search bin/pdflatex
>This program must be run as root..aborting.

**Comment by fenrus75** [comment] 2019-03-01 01:22
I'm fine renaming the old search as grep

there's a real case for grep, and we can make it a good grep, not a half
grep that also tried to be search

**Comment by nsauzede** [comment] 2019-03-01 10:06
@fenrus75 just an off-topic comment : it seems like when replying via email like you did above,
then it posts a comment that renders public one's link with auth token to unsubscribe (mute the thread)
I didn't test unsubscribing someone else, but if it works, then I guess it would be a kind DoS attack (GH bug ?)

**Comment by castulo** [comment] 2019-03-01 20:41
This issue seems to have either an incorrect description or an incorrect title. The title talks about swupd-local-search falling back to the old search and that being confusing, but the description of the issue talks about needing sudo for performing searches. Should we split this into two issues?

**Comment by nsauzede** [comment] 2019-03-02 23:12
In fact my original title did correspond to the description, but has been changed as indicated above.
So my initial report on needing sudo still stands, unless this has been fixed ?
Anyway, feel free to split, triage, etc.. this issue, as long as the one or two bugs identified eventually get fixed

**Comment by otaviobp** [comment] 2019-03-04 17:33
Sorry, the cause of the search requiring sudo was the fallback to the old search. This should be fixed in next swupd release.

Thanks for the report

**Comment by castulo** [comment] 2019-06-07 00:17
This was fixed in swupd version 3.20.0. I'm closing this issue.
Please feel free to reopen the issue if this is still a problem.

**Closed by castulo** 2019-06-07 00:17 UTC
Labels: bug
