### ISSUE TITLE
swupd repair --picky always fixes up .so file from p11-kit package

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/swupd-client#1346] opened 2019-08-21 19:12 UTC
When running a swupd repair --picky, the following message is seen:
```
--picky removing extra files under /usr
REMOVING /usr/lib64/p11-kit-trust.so
```
swupd's view of the system should be what it applies on the system and it shouldn't change afterwards for a system library.

**Comment by rossburton** [comment] 2020-03-04 17:18
I can replicate this and with not just p11-kit-trust.

On my NUC running a full GNOME desktop:

```
$ sudo swupd diagnose --extra-files-only
Diagnosing version 32510
Downloading missing manifests...

Checking for extra files under /usr
 -> Extra file: /usr/share/package-licenses/xcb-proto/COPYING
 -> Extra file: /usr/share/package-licenses/wrapt/LICENSE
 -> Extra file: /usr/share/package-licenses/volume_key/COPYING
 -> Extra file: /usr/share/package-licenses/typing/LICENSE
 -> Extra file: /usr/share/package-licenses/tornado/LICENSE
 -> Extra file: /usr/share/package-licenses/toml/LICENSE
 -> Extra file: /usr/share/package-licenses/ruby/spec_ruby_LICENSE
 -> Extra file: /usr/share/package-licenses/ruby/spec_mspec_LICENSE
 -> Extra file: /usr/share/package-licenses/ruby/lib_bundler_templates_newgem_LICENSE.txt.tt
 -> Extra file: /usr/share/package-licenses/ruby/gems_xmlrpc-0.3.0_LICENSE.txt
 -> Extra file: /usr/share/package-licenses/ruby/gems_test-unit-3.2.9_COPYING
 -> Extra file: /usr/share/package-licenses/ruby/gems_rake-12.3.2_MIT-LICENSE
 -> Extra file: /usr/share/package-licenses/ruby/gems_power_assert-1.1.3_COPYING
 -> Extra file: /usr/share/package-licenses/ruby/gems_net-telnet-0.2.0_LICENSE.txt
 -> Extra file: /usr/share/package-licenses/ruby/gems_did_you_mean-1.3.0_LICENSE.txt
 -> Extra file: /usr/share/package-licenses/ruby/ext_fiddle_libffi-3.2.1_LICENSE
 -> Extra file: /usr/share/package-licenses/ruby/COPYING
 -> Extra file: /usr/share/package-licenses/mosh/COPYING.iOS
 -> Extra file: /usr/share/package-licenses/mosh/COPYING
 -> Extra file: /usr/share/package-licenses/ibus/COPYING.unicode
 -> Extra file: /usr/share/package-licenses/ibus/COPYING
 -> Extra file: /usr/share/package-licenses/chrome-gnome-shell/LICENSE
 -> Extra file: /usr/share/package-licenses/chardet/LICENSE
 -> Extra file: /usr/share/package-licenses/caribou/COPYING
 -> Extra file: /usr/share/package-licenses/cached-property/LICENSE
 -> Extra file: /usr/share/package-licenses/backports.ssl_match_hostname/LICENSE.txt
 -> Extra file: /usr/share/package-licenses/audit/COPYING.LIB
 -> Extra file: /usr/share/package-licenses/audit/COPYING
 -> Extra file: /usr/share/package-licenses/atomicwrites/LICENSE
 -> Extra file: /usr/share/package-licenses/alabaster/LICENSE
 -> Extra file: /usr/share/package-licenses/Babel/docs_license.rst
 -> Extra file: /usr/share/package-licenses/Babel/docs__themes_LICENSE
 -> Extra file: /usr/share/package-licenses/Babel/LICENSE
 -> Extra file: /usr/share/fonts/truetype/liberation/.uuid
 -> Extra file: /usr/share/fonts/truetype/.uuid
 -> Extra file: /usr/share/fonts/terminus/.uuid
 -> Extra file: /usr/share/fonts/roboto/.uuid
 -> Extra file: /usr/share/fonts/noto/.uuid
 -> Extra file: /usr/share/fonts/noto-emoji/.uuid
 -> Extra file: /usr/share/fonts/noto-cjk/.uuid
 -> Extra file: /usr/share/fonts/cantarell/.uuid
 -> Extra file: /usr/share/fonts/adobe-source-code-pro/.uuid
 -> Extra file: /usr/share/fonts/X11/misc/.uuid
 -> Extra file: /usr/share/fonts/X11/encodings/.uuid
 -> Extra file: /usr/share/fonts/X11/Type1/.uuid
 -> Extra file: /usr/share/fonts/X11/TTF/.uuid
 -> Extra file: /usr/share/fonts/X11/OTF/.uuid
 -> Extra file: /usr/share/fonts/X11/75dpi/.uuid
 -> Extra file: /usr/share/fonts/X11/100dpi/.uuid
 -> Extra file: /usr/share/fonts/X11/.uuid
 -> Extra file: /usr/share/fonts/.uuid
 -> Extra file: /usr/lib64/p11-kit-trust.so
 -> Extra file: /usr/lib64/libibus-1.0.so.5.0.521
 -> Extra file: /usr/lib64/libgimpwidgets-2.0.so.0.1000.16
 -> Extra file: /usr/lib64/libgimpui-2.0.so.0.1000.16
 -> Extra file: /usr/lib64/libgimpthumb-2.0.so.0.1000.16
 -> Extra file: /usr/lib64/libgimpmodule-2.0.so.0.1000.16
 -> Extra file: /usr/lib64/libgimpmath-2.0.so.0.1000.16
 -> Extra file: /usr/lib64/libgimpconfig-2.0.so.0.1000.16
 -> Extra file: /usr/lib64/libgimpcolor-2.0.so.0.1000.16
 -> Extra file: /usr/lib64/libgimpbase-2.0.so.0.1000.16
 -> Extra file: /usr/lib64/libgimp-2.0.so.0.1000.16
 -> Extra file: /usr/lib64/libXvMCgallium.so
 -> Extra file: /usr/lib64/haswell/libgimpwidgets-2.0.so.0.1000.16
 -> Extra file: /usr/lib64/haswell/libgimpui-2.0.so.0.1000.16
 -> Extra file: /usr/lib64/haswell/libgimpcolor-2.0.so.0.1000.16
 -> Extra file: /usr/lib64/haswell/libgimpbase-2.0.so.0.1000.16
 -> Extra file: /usr/lib64/haswell/libgimp-2.0.so.0.1000.16
 -> Extra file: /usr/lib64/gimp/2.0/modules/haswell/libdisplay-filter-high-contrast.so
 -> Extra file: /usr/lib64/gimp/2.0/modules/haswell/libdisplay-filter-gamma.so
 -> Extra file: /usr/lib64/gimp/2.0/modules/haswell/libdisplay-filter-color-blind.so
 -> Extra file: /usr/lib64/gimp/2.0/modules/haswell/libdisplay-filter-clip-warning.so
 -> Extra file: /usr/lib64/gimp/2.0/modules/haswell/libcontroller-midi.so
 -> Extra file: /usr/lib64/gimp/2.0/modules/haswell/libcontroller-linux-input.so
 -> Extra file: /usr/lib64/gimp/2.0/modules/haswell/libcolor-selector-wheel.so
 -> Extra file: /usr/lib64/gimp/2.0/modules/haswell/libcolor-selector-water.so
 -> Extra file: /usr/lib64/gimp/2.0/modules/haswell/libcolor-selector-cmyk.so
 -> Extra file: /usr/lib64/gimp/2.0/modules/haswell/
 -> Extra file: /usr/lib32/libXvMCgallium.so
 -> Extra file: /usr/lib/python3.8/site-packages/virtualenv/dirs.py
 -> Extra file: /usr/lib/python3.8/site-packages/virtualenv/__pycache__/dirs.cpython-38.pyc
 -> Extra file: /usr/lib/python3.8/site-packages/virtualenv-20.0.5-py3.8.egg-info/zip-safe
 -> Extra file: /usr/lib/python3.8/site-packages/virtualenv-20.0.5-py3.8.egg-info/top_level.txt
 -> Extra file: /usr/lib/python3.8/site-packages/virtualenv-20.0.5-py3.8.egg-info/requires.txt
 -> Extra file: /usr/lib/python3.8/site-packages/virtualenv-20.0.5-py3.8.egg-info/entry_points.txt
 -> Extra file: /usr/lib/python3.8/site-packages/virtualenv-20.0.5-py3.8.egg-info/dependency_links.txt
 -> Extra file: /usr/lib/python3.8/site-packages/virtualenv-20.0.5-py3.8.egg-info/SOURCES.txt
 -> Extra file: /usr/lib/python3.8/site-packages/virtualenv-20.0.5-py3.8.egg-info/PKG-INFO
 -> Extra file: /usr/lib/python3.8/site-packages/virtualenv-20.0.5-py3.8.egg-info/
 -> Extra file: /usr/lib/python3.8/site-packages/parso-0.6.1-py3.8.egg-info/top_level.txt
 -> Extra file: /usr/lib/python3.8/site-packages/parso-0.6.1-py3.8.egg-info/requires.txt
 -> Extra file: /usr/lib/python3.8/site-packages/parso-0.6.1-py3.8.egg-info/dependency_links.txt
 -> Extra file: /usr/lib/python3.8/site-packages/parso-0.6.1-py3.8.egg-info/SOURCES.txt
 -> Extra file: /usr/lib/python3.8/site-packages/parso-0.6.1-py3.8.egg-info/PKG-INFO
 -> Extra file: /usr/lib/python3.8/site-packages/parso-0.6.1-py3.8.egg-info/
 -> Extra file: /usr/lib/python3.8/site-packages/meson-0.53.1-py3.8.egg-info/top_level.txt
 -> Extra file: /usr/lib/python3.8/site-packages/meson-0.53.1-py3.8.egg-info/requires.txt
 -> Extra file: /usr/lib/python3.8/site-packages/meson-0.53.1-py3.8.egg-info/entry_points.txt
 -> Extra file: /usr/lib/python3.8/site-packages/meson-0.53.1-py3.8.egg-info/dependency_links.txt
 -> Extra file: /usr/lib/python3.8/site-packages/meson-0.53.1-py3.8.egg-info/SOURCES.txt
 -> Extra file: /usr/lib/python3.8/site-packages/meson-0.53.1-py3.8.egg-info/PKG-INFO
 -> Extra file: /usr/lib/python3.8/site-packages/meson-0.53.1-py3.8.egg-info/
 -> Extra file: /usr/lib/python3.8/site-packages/fonttools-4.4.0-py3.8.egg-info/top_level.txt
 -> Extra file: /usr/lib/python3.8/site-packages/fonttools-4.4.0-py3.8.egg-info/requires.txt
 -> Extra file: /usr/lib/python3.8/site-packages/fonttools-4.4.0-py3.8.egg-info/entry_points.txt
 -> Extra file: /usr/lib/python3.8/site-packages/fonttools-4.4.0-py3.8.egg-info/dependency_links.txt
 -> Extra file: /usr/lib/python3.8/site-packages/fonttools-4.4.0-py3.8.egg-info/SOURCES.txt
 -> Extra file: /usr/lib/python3.8/site-packages/fonttools-4.4.0-py3.8.egg-info/PKG-INFO
 -> Extra file: /usr/lib/python3.8/site-packages/fonttools-4.4.0-py3.8.egg-info/
 -> Extra file: /usr/lib/python3.8/site-packages/check_manifest-0.40-py3.8.egg-info/top_level.txt
 -> Extra file: /usr/lib/python3.8/site-packages/check_manifest-0.40-py3.8.egg-info/requires.txt
 -> Extra file: /usr/lib/python3.8/site-packages/check_manifest-0.40-py3.8.egg-info/not-zip-safe
 -> Extra file: /usr/lib/python3.8/site-packages/check_manifest-0.40-py3.8.egg-info/entry_points.txt
 -> Extra file: /usr/lib/python3.8/site-packages/check_manifest-0.40-py3.8.egg-info/dependency_links.txt
 -> Extra file: /usr/lib/python3.8/site-packages/check_manifest-0.40-py3.8.egg-info/SOURCES.txt
 -> Extra file: /usr/lib/python3.8/site-packages/check_manifest-0.40-py3.8.egg-info/PKG-INFO
 -> Extra file: /usr/lib/python3.8/site-packages/check_manifest-0.40-py3.8.egg-info/
```

On my headless server:
```
Checking for extra files under /usr
 -> Extra file: /usr/lib64/p11-kit-trust.so
 -> Extra file: /usr/lib64/libXvMCgallium.so
```

Oddly:

```
$ sudo swupd search-file /usr/lib64/libXvMCgallium.so
Searching for '/usr/lib64/libXvMCgallium.so'
Search term not found
```

**Comment by bryteise** [comment] 2020-03-04 17:21
@rossburton So looking a little myself, it seems like those extra files aren't actually in the distro any longer so picky seems right but it looks instead like swupd update is leaving files behind.

**Comment by otaviobp** [comment] 2020-03-04 17:38
Thanks for the report, but the two problems are unrelated.

The first file is created by post-update scripts and this file is not managed by swupd. So this is the expected behavior (from swupd side) and not a bug. It's worth investigating why the post-update script is creating that file on /usr and if this is really needed. @bryteise ?

The other problem are likely files leftovers from an update. So this is a swupd bug and needs to be fixed. I'll set this issue as a bug for the 2nd problem.

**Comment by otaviobp** [comment] 2020-03-04 17:50
Ops, my mistake.
The first problem (file /usr/lib64/p11-kit-trust.so) is not created by post-update scripts. It's created by ldconfig. So it's a swupd problem. Not sure how to target that though. We need to investigate. I'll open another bug to track that.

**Comment by otaviobp** [comment] 2020-03-04 18:09
I opened 2 new issues to track the 2 different problems (#1347 and #1349).
I'm closing this issue in favor of them.

**Closed by otaviobp** 2020-03-04 18:09 UTC
Labels: bug, medium priority
