### ISSUE TITLE
Slow internet -> unclear if swupd just wastes my bandwidth and retries entire download several times

### ISSUE THREAD

**Issue by sofar** [clearlinux/swupd-client#598] opened 2018-10-03 06:17 UTC
My internet sucks. It's so slow that almost any swupd bundle add, even smaller ones, cause swupd to timeout, even though the downloads progress. As a result, the output suggests that swupd throws the partial files out and starts from scratch, wasting bandwidth and time.

```
# sudo swupd bundle-add keepassxc 
Downloading packs...
	...100%
Error for /var/lib/swupd/pack-keepassxc-from-0-to-24550.tar download: Response 200 - Transferred a partial file
Starting download retry #1 for https://cdn.download.clearlinux.org/update//24550/pack-keepassxc-from-0.tar
Error for /var/lib/swupd/pack-keepassxc-from-0-to-24550.tar download: Response 206 - Transferred a partial file
Starting download retry #2 for https://cdn.download.clearlinux.org/update//24550/pack-keepassxc-from-0.tar
Error for /var/lib/swupd/pack-keepassxc-from-0-to-24550.tar download: Response 206 - No error
Starting download retry #3 for https://cdn.download.clearlinux.org/update//24550/pack-keepassxc-from-0.tar
Error for /var/lib/swupd/pack-keepassxc-from-0-to-24550.tar download: Response 206 - No error
Starting download retry #4 for https://cdn.download.clearlinux.org/update//24550/pack-keepassxc-from-0.tar
Error for /var/lib/swupd/pack-keepassxc-from-0-to-24550.tar download: Response 206 - Transferred a partial file
Starting download retry #5 for https://cdn.download.clearlinux.org/update//24550/pack-keepassxc-from-0.tar
Error for /var/lib/swupd/pack-keepassxc-from-0-to-24550.tar download: Response 206 - Timeout was reached
Starting download of remaining update content. This may take a while...
	...100%
Finishing download of update content...
Installing bundle(s) files...
	...100%
Calling post-update helper scripts.
Successfully installed 1 bundle
```

This is a bug: If the download wasn't stalled, but is just slow, it shouldn't cause the download to interrupt and error, instead it should just continue downloading since data is readily flowing.

Also, the download should be retried if possible at the point it gave an error. It's entirely unclear if it did.

A resumed download is a warning at best, as well.

**Comment by sofar** [comment] 2018-10-03 06:29
btw, this process takes forever. Each timeout is 10+ minutes I think. That's an hour total of time or so? It's much worse with nested bundles.

**Comment by sofar** [comment] 2018-10-03 15:28
The files it's attempting to download are perfectly fine and I can retrieve them manually easily:

```
# curl -L -O https://cdn.download.clearlinux.org/update//25170/files/b695b47d175c310cabc116126598122353d1318506d55f47d8c3d6d6649f4464.tar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1855k  100 1855k    0     0  55949      0  0:00:33  0:00:33 --:--:-- 73038
```

Yet, swupd has failed to update 10x overnight:

```
Oct 03 14:41:45 hades-canyon swupd[25500]: Starting download retry #5 for https://cdn.download.clearlinux.org/update//25080/files/e806c53ea42eb02a8429683f0b4af5162238b3b2f48cc3d2b49f16a18f5b8a0d.tar
Oct 03 14:41:45 hades-canyon swupd[25500]: Starting download retry #5 for https://cdn.download.clearlinux.org/update//25080/files/a82f7c3bc763f1fd786a7be13a7ad1a00575eef97d638749dfdf8b5fbb8ec619.tar
Oct 03 14:41:45 hades-canyon swupd[25500]: Starting download retry #5 for https://cdn.download.clearlinux.org/update//25170/files/495b4014f7baeb1bd79fc93f994f91ac167e7c54954875338eeca369e525a176.tar
Oct 03 14:41:45 hades-canyon swupd[25500]: Starting download retry #5 for https://cdn.download.clearlinux.org/update//25160/files/0091c6a702f54c67002f4444d08f2d8a5a164ca6cf0cb1eee8ad40c383645d8b.tar
Oct 03 14:41:45 hades-canyon swupd[25500]: Starting download retry #5 for https://cdn.download.clearlinux.org/update//25360/files/f85467314c000259fb4a2add6a4b6064243bb310251271e76515a50ab0e978c6.tar
Oct 03 14:41:45 hades-canyon swupd[25500]: Starting download retry #5 for https://cdn.download.clearlinux.org/update//25150/files/cd04a6819575ff625dca0a729a5caeabd83396abe6c5cc65e9500c50a23d64c1.tar
Oct 03 14:41:45 hades-canyon swupd[25500]: Starting download retry #5 for https://cdn.download.clearlinux.org/update//25080/files/bff3f450c9a070c158c92abb93f96a4918b874a826c55a193710d57e4ae21243.tar
Oct 03 14:41:45 hades-canyon swupd[25500]: Starting download retry #5 for https://cdn.download.clearlinux.org/update//25160/files/0f7c39ab38c635616f0923fcfe30960d9d4396b41ae9a7721182559252339915.tar
Oct 03 14:41:45 hades-canyon swupd[25500]: Starting download retry #5 for https://cdn.download.clearlinux.org/update//25080/files/ceaf183f6764b47460aa5e3dfd32bd945b2ee009550a2dbd75b35edc357a2967.tar
```

Completely broken, my system can't update. It has tried several times and each time prematurely disconnects downloads causing the update to fail.

**Comment by sofar** [comment] 2018-10-03 15:38
Code seems fine? I don't see any offending `curl_easy_setopt` lines. Perhaps it's doing too many parallel downloads and swamping the interface?

**Comment by evil-brain** [comment] 2018-10-03 16:55
From IRC the swupd version is: 3.17.13

May be related to parallel downloads.

**Comment by sofar** [comment] 2018-10-03 19:36
After several tries with 3.17.15, it seems to have completed pack downloads, but now it still errors out on fullfile downloads. If these are not continued, I am stuck in an endless loop redownloading them.


```
# swupd update -D 1
Update started.
Preparing to update from 24620 to 25380
Downloading packs...
	...100%

Statistics for going from version 24620 to version 25380:

    changed bundles   : 42
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 151946
    new files         : 59646
    deleted files     : 28065

Starting download of remaining update content. This may take a while...
	...0%Error for /var/lib/swupd/download/.5f5830eedd49d7d06fc594785883d07b341911562d387ad8757af88b9e622ff4.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.19a52496cbea43c52d29b46278312c5363c74af9040ea764745c4e65ef128c75.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.9c68c392717fd9ac8b6aa3522b93dc79a8e6ebe22a643cf785ebc587aaed6f2f.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.ba824d910dfe75c1d83fe8dd706ab8d945df45444d158d73850565c38141e5d9.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.605cb7d840547e62a41c894cdee6a58e38f4f5098866ae2a737573e0d28baf24.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.5529caad74a93ce73ab6690b186440a74e8174a7e669d91d7580ba72a8912e2c.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.f21923eabe3b65d76d104294bf945ad9ece6b57fd7f9ce744a87b1c7ecdcca06.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.48748ce7a25c013dbaafb340d4ab160f1e4df31c601d56ef0bff44898947ecd8.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.c55ca65ce0f8619d87080adedf8fd0800d9ffd221c337f11e1fa64f3f353af30.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.df1c3d779ac26df3df7df7ab075f596e7bc1b5258658f170cb276409e97b285f.tar download: Response 200 - Timeout was reached
Error for /var/lib/swupd/download/.ad67e5d041616aea3959f05a494a0c58e7dbc19f9c8298b953414ddb270f8311.tar download: Response 0 - Timeout was reached
Error for /var/lib/swupd/download/.63750d126611e01b9088c509087b685013e1d1a00c8c7b3f4fa6d970d36368a2.tar download: Response 0 - Timeout was reached
Error for /var/lib/swupd/download/.e11c2a41cc9a52ae8cd89ef19f4cd350337915bb3bd36be81087b03a176e1922.tar download: Response 0 - Timeout was reached
Error for /var/lib/swupd/download/.df0969ff02f537d50942ce7840ca70e698d8c645f3a0251e48bdb1a784234510.tar download: Response 0 - Timeout was reached
Error for /var/lib/swupd/download/.f269e896016446d6138762d3d6633fe7743cdd84f6864258f38135ea6391b91e.tar download: Response 0 - Timeout was reached
Error for /var/lib/swupd/download/.29b4df154cfa86b8f6a3350eaeed70ed9700468803a9379a79d1869f7fc88cea.tar download: Response 0 - Timeout was reached
Error for /var/lib/swupd/download/.e3273f9f6bb3db0d3a3c0dbf8b07407030b2a2340abbf8caf805f02f1d7b076b.tar download: Response 0 - Timeout was reached
Error for /var/lib/swupd/download/.13111451c6b724dfc358612c9351bd0e04a689d604a3e6de01b1307c272ecbe5.tar download: Response 0 - Timeout was reached
Error for /var/lib/swupd/download/.75c7044e64065d1ba4744845654fee45126bac95b82f2513fb9392af023e9b65.tar download: Response 0 - Timeout was reached
Error for /var/lib/swupd/download/.1c1ae6979acc246e37b4b46f819f7f3fcdeb66c0848139fda46832d62c3eb79a.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.9b90cc1f58c715d58748b2cf555f03af6f86548af68617967d5144deb0ed1431.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.fffc2c2c0daa38e5d99dae93a05144d85b172aab4efd17f4bf718e970162f3d5.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.c4f1a068690dbf200b597d5ada9749dfa3df7af904facec9be23cc889548c080.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.2e7f7472a0fe0b759e5b5c84e1fa09519b75489bdac165e6d6feae413c9597f6.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.02a332941ed6b3d15480fc03d5360427e1b6bcdd82df99bf5334ec04f46bb590.tar download: Response 200 - Transferred a partial file
	...16%Error for /var/lib/swupd/download/.dc940e54d3d5f27aeeec9e02ad82e455cb6991cd4fb4dff3af38c01dd3e63748.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.a013abf50e7dee3e07da9eb8f2db5a890b9b6306f48002f46f767c4d496fab9f.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.b384ebe36caf8978230408b8f2aade1a5e61dd329961288bb65b365b30447574.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.8d4ede00a64351b27f2ea785602a00d5ea9ef9ca46bd80ba9ad72c9ee9275225.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.c4fa649a66ec3da740808c2a5e479e345b2b77d6e53b440ab084cb2f02c8decb.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.576fbdfc8e065d709503295df0e8f4d958d296632029a3e632adeda542f59fed.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.6d092ec37a4a45d1f516aecff144ee21783fe94e2f8cc4ea93ff963eabffbfd3.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.9ed616fcd1ec4e788372582a0b1b3fbd4e6a4e623a73caf95da1390a30a8f186.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.a98a03a87966154daf3cf6e6afe35496dd8ced869153d4b8c4855b49896a2fbe.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.a369ad2468e4162a450e55eb1e508c13be882f2532462fa2adedcbf89bf290cf.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.256a0f7a9e9c24307edf73e2eea078eb36891080d02235e900f9399e041d8525.tar download: Response 200 - Transferred a partial file
Error for /var/lib/swupd/download/.481bc868e349a65dbca826f93b4761c35fad0320547331edd5b3b8face728465.tar download: Response 200 - Transferred a partial file
	...18%
```

**Comment by evil-brain** [comment] 2018-10-03 23:00
The pack download failures do appear to be related to MAX_XFER values, 5 results in no problems (on my connection, on my machine, with the server as busy as it was when I tested), 10 failed 1 file, and the old default, 25, failed many files.

A partial workaround is to have the -D option apply to both pack downloads AND fullfile downloads. This would be a good start.

I'll also add more verbosity to the curl failures - Transferred a partial file is pretty obvious, but how much was not downloaded? Are we able to resume these failures, and are they being resumed?

I can only recreate on `https://cdn.download.clearlinux.org/update`.
`https://download.clearlinux.org/update`, and `internal mirror url` both don't reproduce. I want to test parallel downloads on the CDN independent of swupd. Maybe it's just the server getting swamped?

**Comment by evil-brain** [comment] 2018-10-05 00:07
characterized the failures a bit more today. I used -D 25 for all the numbers below.
Number of failures seems fairly random (from 1 to 20), but they do increase when I add more load to the network (I'm WFH, so I just fired off some large downloads to use most of my bandwidth)
Here's some interesting data:

Bytes Downloaded | Delta from Content-Size
------------ | -------------
26928 | 1832400
27632 | 93993976
27963 | 399599941
27960 | 331527228
27312 | 42497416
27957 | 449003283
25808 | 6325840
27957 | 230428211
27276 | 2762840
27852 | 891768
26548 | 28929512
26972 | 97905120
26800 | 52365920
27020 | 5588808
27961 | 453736607
26152 | 88981344

Average Bytes downloaded is 27256 and the range for bytes downloaded is only 2155 bytes - seems the downloads fail very early and fairly consistently when we get partial downloads. I don't know what this means, yet, if anything - but it may be interesting.

I tried to verify that swupd resumes the file downloads, but I need to work at it a little more.
Output:
```
Starting download retry #1 for https://cdn.download.clearlinux.org/update/25160/pack-os-installer-from-0.tar
Schedule resume for /home/blovin/swupd_verify_testing/testing/var/lib/swupd/pack-os-installer-from-0-to-25160.tar
Size of file: 140564
        Response: 206
        URL: https://cdn.download.clearlinux.org/update/25160/pack-os-installer-from-0.tar
curl_ret: 0
response: 206
Error for /home/blovin/swupd_verify_testing/testing/var/lib/swupd/pack-os-installer-from-0-to-25160.tar download: Response 206 - No error
Starting download retry #2 for https://cdn.download.clearlinux.org/update/25160/pack-os-installer-from-0.tar
Schedule resume for /home/blovin/swupd_verify_testing/testing/var/lib/swupd/pack-os-installer-from-0-to-25160.tar
Size of file: 28815496
        Response: 206
        URL: https://cdn.download.clearlinux.org/update/25160/pack-os-installer-from-0.tar
curl_ret: 0
response: 206
Error for /home/blovin/swupd_verify_testing/testing/var/lib/swupd/pack-os-installer-from-0-to-25160.tar download: Response 206 - No error
Starting download retry #3 for https://cdn.download.clearlinux.org/update/25160/pack-os-installer-from-0.tar
Schedule resume for /home/blovin/swupd_verify_testing/testing/var/lib/swupd/pack-os-installer-from-0-to-25160.tar
Size of file: 140564
        Response: 206
        URL: https://cdn.download.clearlinux.org/update/25160/pack-os-installer-from-0.tar
curl_ret: 0
response: 206
Error for /home/blovin/swupd_verify_testing/testing/var/lib/swupd/pack-os-installer-from-0-to-25160.tar download: Response 206 - No error
Starting download retry #4 for https://cdn.download.clearlinux.org/update/25160/pack-os-installer-from-0.tar
Schedule resume for /home/blovin/swupd_verify_testing/testing/var/lib/swupd/pack-os-installer-from-0-to-25160.tar
Size of file: 28815496
        Response: 206
        URL: https://cdn.download.clearlinux.org/update/25160/pack-os-installer-from-0.tar
curl_ret: 0
response: 206
Error for /home/blovin/swupd_verify_testing/testing/var/lib/swupd/pack-os-installer-from-0-to-25160.tar download: Response 206 - No error
Starting download retry #5 for https://cdn.download.clearlinux.org/update/25160/pack-os-installer-from-0.tar
Schedule resume for /home/blovin/swupd_verify_testing/testing/var/lib/swupd/pack-os-installer-from-0-to-25160.tar
Size of file: 140564
        Response: 206
        URL: https://cdn.download.clearlinux.org/update/25160/pack-os-installer-from-0.tar
curl_ret: 28
response: 206
Error for /home/blovin/swupd_verify_testing/testing/var/lib/swupd/pack-os-installer-from-0-to-25160.tar download: Response 206 - Timeout was reached
```
`Size of file` is the result from stat on the filepath - weird results here, retries 1, 3, and 5 have a size of 140564. 2 and 4 have a size of 28815496. So it seems like the download does NOT resume across retries, but I can't explain why the size appears to 'toggle' back and forth between two values.

I also cannot explain why we get a 206 "partial file" response, but curl_ret is CURLE_OK until the last retry where curl_ret (28) is CURLE_OPERATION_TIMEDOUT. I think I need to verify these findings and debug more to determine if retries are working correctly in this case.

To fix this issue:
1. I think we need to consider changing MAX_XFER to a smaller value, or dynamically reduce MAX_XFER if we start getting partial file downloads.
2. Fix bug #604 to mitigate partial downloads when downloading fullfiles
3. Verify if retries are working. I may just run 'watch -n.5 du *.tar' in /var/lib/swupd during these failures and observe directly what's happening.

**Comment by sofar** [comment] 2018-10-05 02:51
I disabled all parallel downloads in the code and built a local copy. So far it's been running at the worst bandwidth level at the day and not a single timeout has occurred yet.

**Comment by sofar** [comment] 2018-10-05 02:54
#604 doesn't really fix it. It just allows a user to dictate parallel max defaults.

What I think needs to happen is after 2-3 retries, parallel downloads are permanently disabled for the rest of the duration. Leaving parallel downloads enabled after we had severe download errors is just not very smart - we know we have issues, but downloading must continue. Maybe try 3x with parallel downloads, each time reducing the amount of parallel downloads, and after the 3rd, try 3x without any parallel downloads?

e.g. 25 -> 12 -> 6 -> 1 -> 1 -> 1 ?

**Comment by otaviobp** [comment] 2018-10-05 17:06
> What I think needs to happen is after 2-3 retries, parallel downloads are permanently disabled for the rest of the duration. Leaving parallel downloads enabled after we had severe download errors is just not very smart - we know we have issues, but downloading must continue. Maybe try 3x with parallel downloads, each time reducing the amount of parallel downloads, and after the 3rd, try 3x without any parallel downloads?

I like this approach

**Comment by otaviobp** [comment] 2018-10-05 17:16
@evil-brain Did you test that with multi-threads? Because multi-threads is suppose to fix at least one cause of timeouts.

**Comment by evil-brain** [comment] 2018-10-05 17:33
@otaviobp Yes, all testing was with mutli-threads.

I like the approach above as well, I'll implement and start testing it.

**Comment by sofar** [comment] 2018-10-06 16:02
Update.

I still can't fully update. At this point I seem to be stuck on a single fullfile that fails to download. We're now 2+ days further and even without parallel downloads, I still get hit with timeouts:

```
# ~sofar/git/swupd-client/swupd update -D 1
Update started.
Preparing to update from 24620 to 25430
Downloading packs...
	...100%

Statistics for going from version 24620 to version 25430:

    changed bundles   : 44
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 208307
    new files         : 65281
    deleted files     : 33308

Starting download of remaining update content. This may take a while...
	...29%Error for /var/lib/swupd/download/.52af86b4becfe7ede9a5498424eeeb8a93aa9569c4a199da53e312bfc43c63e1.tar download: Response 200 - Transferred a partial file

	...100%
Finishing download of update content...
Starting download retry #1 for https://cdn.download.clearlinux.org/update//25170/files/52af86b4becfe7ede9a5498424eeeb8a93aa9569c4a199da53e312bfc43c63e1.tar
Error for /var/lib/swupd/download/.52af86b4becfe7ede9a5498424eeeb8a93aa9569c4a199da53e312bfc43c63e1.tar download: Response 206 - No error
Starting download retry #2 for https://cdn.download.clearlinux.org/update//25170/files/52af86b4becfe7ede9a5498424eeeb8a93aa9569c4a199da53e312bfc43c63e1.tar
Error for /var/lib/swupd/download/.52af86b4becfe7ede9a5498424eeeb8a93aa9569c4a199da53e312bfc43c63e1.tar download: Response 206 - No error
Starting download retry #3 for https://cdn.download.clearlinux.org/update//25170/files/52af86b4becfe7ede9a5498424eeeb8a93aa9569c4a199da53e312bfc43c63e1.tar
Error for /var/lib/swupd/download/.52af86b4becfe7ede9a5498424eeeb8a93aa9569c4a199da53e312bfc43c63e1.tar download: Response 206 - No error
Starting download retry #4 for https://cdn.download.clearlinux.org/update//25170/files/52af86b4becfe7ede9a5498424eeeb8a93aa9569c4a199da53e312bfc43c63e1.tar
Error for /var/lib/swupd/download/.52af86b4becfe7ede9a5498424eeeb8a93aa9569c4a199da53e312bfc43c63e1.tar download: Response 206 - No error
Starting download retry #5 for https://cdn.download.clearlinux.org/update//25170/files/52af86b4becfe7ede9a5498424eeeb8a93aa9569c4a199da53e312bfc43c63e1.tar
Error for /var/lib/swupd/download/.52af86b4becfe7ede9a5498424eeeb8a93aa9569c4a199da53e312bfc43c63e1.tar download: Response 206 - No error
Staging file content
File staging failed: /usr/lib64/libQt5WebEngineCore.so.5.11.1
Calling post-update helper scripts.
none
Update took 30459.8 seconds
69647 files were not in a pack
root@hades-canyon /var/log # 
root@hades-canyon /var/log # echo $?
2
root@hades-canyon /var/log # stat /usr/lib64/libQt5WebEngineCore.so.5.11.1
  File: /usr/lib64/libQt5WebEngineCore.so.5.11.1
  Size: 107860176 	Blocks: 210672     IO Block: 4096   regular file
Device: 10303h/66307d	Inode: 16683780    Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-10-06 04:04:08.034138133 -0700
Modify: 2018-07-07 17:27:19.000000000 -0700
Change: 2018-10-06 04:04:08.512138096 -0700
 Birth: -
```

Every time I download, /var/lib/swupd is mostly emptied, so I'm re-downloading several GB of data *again* and *again*. This should absolutely not happen....

**Comment by sofar** [comment] 2018-10-06 16:03
wait, despite the staging content error, it... actually did update?

**Comment by sofar** [comment] 2018-10-06 19:38
yep, it actually did. I'm slighty disturbed, but, it's updated and verifies OK. XD

**Closed** 2019-01-16 16:42 UTC
Labels: bug, high priority

**Comment by sofar** [comment] 2019-02-01 04:59
I'll remove the local limit I have here and monitor to see if this becomes reliable again. Thanks.
